const FETCH_QUIZ_LIST_START = 'FETCH_QUIZ_LIST_START';
const FETCH_QUIZ_LIST_SUCCESS = 'FETCH_QUIZ_LIST_SUCCESS';
const FETCH_QUIZ_LIST_ERROR = 'FETCH_QUIZ_LIST_ERROR';

const FETCH_QUIZ_START = 'FETCH_QUIZ_START';
const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
const FETCH_QUIZ_ERROR = 'FETCH_QUIZ_ERROR';

const SET_QUIZ_ANSWER_RESULTS = 'SET_QUIZ_ANSWER_RESULTS';
const SET_QUIZ_ACTIVE_QUESTION = 'SET_QUIZ_ACTIVE_QUESTION';
const FINISH_QUIZ = 'FINISH_QUIZ';
const RETRY_QUIZ = 'RETRY_QUIZ';

export {
    FETCH_QUIZ_LIST_START,
    FETCH_QUIZ_LIST_SUCCESS,
    FETCH_QUIZ_LIST_ERROR,
    FETCH_QUIZ_START,
    FETCH_QUIZ_SUCCESS,
    FETCH_QUIZ_ERROR,
    SET_QUIZ_ANSWER_RESULTS,
    SET_QUIZ_ACTIVE_QUESTION,
    FINISH_QUIZ,
    RETRY_QUIZ
}