const FETCH_QUIZES_START = 'FETCH_QUIZES_START';
const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS';
const FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR';

export {
    FETCH_QUIZES_START,
    FETCH_QUIZES_SUCCESS,
    FETCH_QUIZES_ERROR
}